language: rust
before_script:
  - rustup component add rustfmt
  - rustup component add clippy
rust:
  - stable
script:
  - cargo fmt --all -- --check
  - cargo clippy --all-targets --all-features
  - cargo build
  - cargo test --test hector_test
  - cargo test --test query_test
  - cargo test --all --exclude hector_test --exclude query_test
