language: rust
before_script:
  - rustup component add rustfmt
  - rustup component add clippy
rust:
  - stable
script:
  - cargo fmt --all -- --check
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo build
  - cargo test
